project:
  type: website
  output-dir: ../docs

website:
  title: "Riginos Research Group"
  navbar:
    left:
      - href: index.qmd
        text: Cynthia Riginos
      - href: UQ.qmd
        text: UQ Research Group
      - href: EvoReef.qmd
        text: EvoReef Group

  page-footer:
    left: "&copy; Cynthia Riginos, 2026"
     

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    toc-depth: 3

editor: visual
lightbox: true


